
#Range: min = 0, max = 2147483647
["Basic Enregy Cell"]
	transfer = "250"
	capacity = "1000000"

["Hardened Enregy Cell"]
	transfer = "1000"
	capacity = "5000000"

["Blazing Enregy Cell"]
	transfer = "4000"
	capacity = "12000000"

["Niotic Enregy Cell"]
	transfer = "20000"
	capacity = "25000000"

["Spirited Enregy Cell"]
	transfer = "500000"
	capacity = "100000000"

