#Range for every direction, Eg: range of 4 = 9X9, range of 1 = 3X3 etc..., [default: 4]
#Range: 1 ~ 16
range = 4

#
#Range: min = 0, max = 2147483647
["Basic Energizing Rod"]
	capacity = "10000"
	transfer = "60"
	energizing = "40"

["Hardened Energizing Rod"]
	capacity = "30000"
	transfer = "140"
	energizing = "100"

["Blazing Energizing Rod"]
	capacity = "90000"
	transfer = "400"
	energizing = "300"

["Niotic Energizing Rod"]
	capacity = "200000"
	transfer = "1000"
	energizing = "700"

["Spirited Energizing Rod"]
	capacity = "500000"
	transfer = "2800"
	energizing = "1200"

