#Range for every direction, Eg: range of 4 = 9X9, range of 1 = 3X3 etc..., [default: 4]
#Range: 1 ~ 16
range = 4

#
#Range: min = 0, max = 2147483647
["Basic Energizing Rod"]
	energizing = "40"
	transfer = "60"
	capacity = "10000"

["Hardened Energizing Rod"]
	energizing = "100"
	transfer = "140"
	capacity = "30000"

["Blazing Energizing Rod"]
	energizing = "300"
	transfer = "400"
	capacity = "90000"

["Niotic Energizing Rod"]
	energizing = "700"
	transfer = "1000"
	capacity = "200000"

["Spirited Energizing Rod"]
	energizing = "1200"
	transfer = "2800"
	capacity = "500000"

