
[oregeneration]
	#Determines the size of an amber vein.
	#Range: 1 ~ 32
	amber_size = 8
	#Determines the rarity of amber veins.
	#Range: 1 ~ 200
	amber_weight = 2
	#Determines the size of a moonstone vein.
	#Range: 1 ~ 32
	moonstone_size = 8
	#Determines the rarity of moonstone veins.
	#Range: 1 ~ 200
	moonstone_weight = 5
	#Determines the size of a fiery glass vein.
	#Range: 1 ~ 32
	fiery_glass_size = 8
	#Determines the rarity of fiery glass veins.
	#Range: 1 ~ 200
	fiery_glass_weight = 6
	#Determines the size of a rockroot vein.
	#Range: 1 ~ 32
	rockroot_size = 3
	#Determines the rarity of rockroot veins.
	#Range: 1 ~ 200
	rockroot_weight = 16
	#Whether to have ores from this mod spawn at all.
	generate_ores = true

[droprate]
	#Rate of hemp seed drops from grass blocks.
	#Range: 0 ~ 100
	hemp_seed_rate = 8
	#Whether to have seeds from this mod drop from grass at all.
	drop_seeds = true

