
#Basalt Generation
[basalt]
	#Generate basalt in the world [true / false]
	basaltGeneration = true
	#Size of basalt pockets [0-100, default: 33]
	#Range: 0 ~ 100
	basaltSize = 33
	#Chances of basalt pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	basaltChance = 10
	#Minimal height for basalt pocket generation, [0-255, default: 0]
	#Range: 0 ~ 255
	basaltMinHeight = 0
	#Maximal height for basalt pocket generation [0-255, default: 40]
	#Range: 0 ~ 255
	basaltMaxHeight = 30

#Slate Generation
[slate]
	#Generate slate in the world [true / false]
	slateGeneration = true
	#Size of slate pockets [0-100, default: 33]
	#Range: 0 ~ 100
	slateSize = 33
	#Chances of slate pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	slateChance = 10
	#Minimal height for slate pocket generation, [0-255, default: 40]
	#Range: 0 ~ 255
	slateMinHeight = 45
	#Maximal height for slate pocket generation [0-255, default: 70]
	#Range: 0 ~ 255
	slateMaxHeight = 75

#Marble Generation
[marble]
	#Generate marble in the world [true / false]
	marbleGeneration = true
	#Size of marble pockets [0-100, default: 25]
	#Range: 0 ~ 100
	marbleSize = 20
	#Chances of marble pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	marbleChance = 10
	#Minimal height for marble pocket generation, [0-255, default: 50]
	#Range: 0 ~ 255
	marbleMinHeight = 60
	#Maximal height for marble pocket generation [0-255, default: 100]
	#Range: 0 ~ 255
	marbleMaxHeight = 100

#Gneiss Generation
[gneiss]
	#Generate gneiss in the world [true / false]
	gneissGeneration = true
	#Size of gneiss pockets [0-100, default: 25]
	#Range: 0 ~ 100
	gneissSize = 33
	#Chances of gneiss pocket being generated [0-100, default: 10]
	#Range: 0 ~ 100
	gneissChance = 10
	#Minimal height for gneiss pocket generation, [0-255, default: 50]
	#Range: 0 ~ 255
	gneissMinHeight = 35
	#Maximal height for gneiss pocket generation [0-255, default: 100]
	#Range: 0 ~ 255
	gneissMaxHeight = 65

