
[tp]
	#If true, villagers who wander into Floo fires MAY teleport to a random fireplace. Never consumes Floo Powder.
	villagers = false
	#If true, dropped items that touch Floo fires WILL teleport to a random fireplace. Never consumes Floo Powder.
	items = false
	#As with villagers, but for Sheep, Cows, Spiders, Silverfish, Zombies etc. Never consumes Floo Powder.
	miscmobs = false

