
[multi-tool]
	#Max range Multi-Tool can edit blocks [Default: 128]
	#Range: > 0
	reach = 128
	#Cost that is added on to every place [Default: 100]
	#Range: > 0
	placeBaseCost = 100
	#Cost per meter away [Default: 10]
	#Range: > 0
	costPerMeterAway = 10
	#Cost that is added on to every block break [Default: 100]
	#Range: > 0
	breakBaseCost = 100
	#Multiples the Hardness Cost by this. [Default: 1]
	#Range: > 0
	breakCostMultiplier = 1
	#0 - None, 1 Block Place Preview, 2 Block Break Preview, 3 Place/Break Preview. [Default: 1]
	#Range: 0 ~ 3
	assistMode = 3

[multi-armor]
	#Base cost of any defensive action. [Default: 10]
	#Range: > 0
	baseCost = 10
	#How much energy is used base per damage. [Default: 100]
	#Range: 0.0 ~ 3.4028234663852886E38
	damageMultiplier = 100.0
	#Energy Multiplier for Absolute Damage. [Default: 10]
	#Range: 0.0 ~ 3.4028234663852886E38
	absoluteDamageMultiplier = 10.0
	#Energy Multiplier for Unblockable Damage. [Default: 10]
	#Range: 0.0 ~ 3.4028234663852886E38
	unblockableMultiplier = 10.0
	#Max level to feed up too. [Default By Vanilla MC: 20]
	#Range: > 0
	maxFoodLevel = 20
	#Max saturation level to add too. [Default By Vanilla MC: 5
	#Range: 0.0 ~ 3.4028234663852886E38
	maxSaturationLevel = 5.0
	#Energy Cost per food amount to fill. [Default: 1000]
	#Range: > 0
	costPerFood = 1000
	#Energy Cost per Saturation amount to fill. [Default: 4000]
	#Range: 0.0 ~ 3.4028234663852886E38
	costPerSaturation = 4000.0
	#Energy Cost to remove a potion effect. [Default: 10000]
	#Range: > 0
	removeEffect = 10000
	#Energy Cost per health amount to heal. [Default: 5000]
	#Range: > 0
	costPerHealth = 5000
	#Energy to Extinguish the player. [Default: 1000]
	#Range: > 0
	extinguishCost = 1000
	#Energy per Air Tick. [Default: 10]
	#Range: > 0
	costPerAir = 10
	#Energy Per Tick to use No Clip. [Default: 100000]
	#Range: > 0
	noClipEnergyPerTick = 100000
	#Max flight speed. [Default: 5]
	#Range: 0.0 ~ 3.4028234663852886E38
	maxFlightSpeed = 5.0
	#Energy used per tick while flying. [Default:10]
	#Range: > 0
	energyPerTickFlying = 10
	#Energy use multiple per flight speed. [Default: 10]
	#Range: 0.0 ~ 3.4028234663852886E38
	energyMultiplerPerFlightSpeed = 10.0
	#Max ground speed. [Default: 10]
	#Range: 0.0 ~ 3.4028234663852886E38
	maxGroundSpeed = 10.0
	#Energy per block walked. [Default: 10]
	#Range: 0.0 ~ 3.4028234663852886E38
	energyPerBlockWalked = 10.0
	#Energy use multiplier per ground speed. [Default: 5]
	#Range: 0.0 ~ 3.4028234663852886E38
	energyMultiplierPerGroundSpeed = 5.0

[development]
	#Stuff not deemed to be safe yet. IE World Corrupting / Crashing. [Default: false]
	wipStuff = false

[resolution]
	#Resolution for Blocks. [Default: 256]
	#Range: > 1
	blockResolution = 256
	#Resolution for Items. [Default: 256]
	#Range: > 1
	itemResolution = 256
	#Resolution for Multi-Armor. [Default: 256]
	#Range: > 1
	multiArmorResolution = 256

[purifier]
	#Energy Per Operation Base. [Default: 10000]
	#Range: > 0
	energyPerOperation = 10000
	#Energy Per Hardness of Block. [Default: 1000]
	#Range: > 0
	energyPerHardness = 1000

[special]
	#Fix for rending while noClip is active. May cause issues with some other mods. [Default: true]
	noClipRenderFix = true
	#Do not change without reading https://github.com/CJ-MC-Mods/Overloaded/wiki/Minecraft-Inventory-Mechanic-Bugs#slots-for-infinity-barrel. Reduces performance for compatibility. [Default:: false]
	infinityBarrelAdditionalSlot = false

[ray-gun]
	#Energy used per shot. [Default: 100000]
	#Range: > 0
	energyPerShot = 100000
	#Max range to shoot. [Default: 128]
	#Range: > 0
	maxRange = 128

[rail-gun]
	#Minimum energy used per shot. [Default: 1,000,000]
	#Range: > 0
	minEnergy = 10000000
	#Maximum energy used per shot. [Default: 2,000,000,000]
	#Range: > 0
	maxEnergy = 2000000000
	#Energy change step (via scroll wheel). [Default: 10,000,000]
	#Range: > 0
	stepEnergy = 10000000
	#Max range to shoot. [Default: 128]
	#Range: > 0
	maxRange = 128
	#Damage per RF(FE) spent. [Default: 0.00001
	#Range: 0.0 ~ 3.4028234663852886E38
	damagePerRF = 9.999999747378752E-6
	#Distance knockback per RF(FE) spent. [Default: 0.000001
	#Range: 0.0 ~ 3.4028234663852886E38
	knockbackPerRF = 9.999999974752427E-7

[production]
	#Energy per cook time to use to smelt items. [Default: 10]
	#Range: > 0
	energyPerCookTime = 10

