
#Miscellaneous options
[general]
	#Disable to enchant the travel bag [default:false]
	disable_enchanted_travel_bag = false
	#Disable the Gluttony slot [default:false]
	disable_gluttony_slot = false
	#Speed of extraction in ticks of the Gluttony slot [20..1000|default:20]
	#Range: 20 ~ 1000
	gluttony_slot_speed = 20

