
[ore_protector]
	#Set to false if you want the Pigmen to attack when using Silk Touch Tools
	silkEffect = true
	#Add Blocks to be protected by Pigmen (Example: 'minecraft:glowstone')
	protectedBlocks = ["bno:netheremerald_ore", "bno:netherdiamond_ore", "bno:netherlapis_ore", "bno:netherredstone_ore", "bno:nethergold_ore", "bno:nethersilver_ore", "bno:netheriron_ore", "bno:netherlead_ore", "bno:nethernickel_ore", "bno:nethercoal_ore", "bno:nethercopper_ore", "bno:netheraluminum_ore", "bno:nethertin_ore", "bno:netheruranium_ore", "minecraft:glowstone", "minecraft:nether_quartz_ore"]
	#If set to 'true' Pigmen will protect Nether Ores
	pigmanGuard = true
	#Set range that Pigmen will aggro when mining ores(Default = 16)
	#Range: 0 ~ 64
	protectionRange = 16

[ore_generation]

	[ore_generation.nickel]
		#Set Nickel Max Spawn Height (Default = 50)
		#Range: 0 ~ 125
		nickelMaxHeight = 50
		#Set Nickel Min Spawn Height (Default = 30)
		#Range: 0 ~ 120
		nickelMinHeight = 30
		#Set Max Nickel Vein Size (Default = 8)
		#Range: 0 ~ 32
		nickelVeinSize = 8
		#Set Nickel Spawn Chance (Default = 4)
		#Range: 0 ~ 64
		nickelChance = 4

	[ore_generation.aluminum]
		#Set Aluminum Spawn Chance (Default = 10)
		#Range: 0 ~ 64
		aluminumChance = 10
		#Set Aluminum Max Spawn Height (Default = 110)
		#Range: 0 ~ 125
		aluminumMaxHeight = 110
		#Set Max Aluminum Vein Size (Default = 8)
		#Range: 0 ~ 32
		aluminumVeinSize = 8
		#Set Aluminum Min Spawn Height (Default = 75)
		#Range: 0 ~ 120
		aluminumMinHeight = 75

	[ore_generation.lead]
		#Set Lead Spawn Chance (Default = 8)
		#Range: 0 ~ 64
		leadChance = 8
		#Set Max Lead Vein Size (Default = 8)
		#Range: 0 ~ 32
		leadVeinSize = 8
		#Set Lead Max Spawn Height (Default = 110)
		#Range: 0 ~ 125
		leadMaxHeight = 110
		#Set Lead Min Spawn Height (Default = 40)
		#Range: 0 ~ 120
		leadMinHeight = 40

	[ore_generation.gold]
		#Set Gold Max Spawn Height (Default = 80)
		#Range: 0 ~ 125
		goldMaxHeight = 80
		#Set Max Gold Vein Size (Default = 9)
		#Range: 0 ~ 64
		goldVeinSize = 9
		#Set Gold Spawn Chance (Default = 4)
		#Range: 0 ~ 64
		goldChance = 4
		#Set Gold Min Spawn Height (Default = 40)
		#Range: 0 ~ 120
		goldMinHeight = 40

	[ore_generation.diamond]
		#Set Diamond Min Spawn Height (Default = 90)
		#Range: 0 ~ 120
		diamondMinHeight = 90
		#Set Diamond Spawn Chance (Default = 3)
		#Range: 0 ~ 32
		diamondChance = 3
		#Set Max Diamond Vein Size (Default = 8)
		#Range: 0 ~ 36
		diamondVeinSize = 8
		#Set Diamond Max Spawn Height (Default = 125)
		#Range: 0 ~ 125
		diamondMaxHeight = 125

	[ore_generation.world_generation]
		#Generate Nickel Ore
		nickel = true
		#Generate Aluminum Ore
		aluminum = true
		#Generate Lead Ore
		lead = true
		#Generate Gold Ore
		gold = true
		#Generate Diamond Ore
		diamond = true
		#Generate Tin Ore
		tin = true
		#Generate Coal Ore
		coal = true
		#Generate Iron Ore
		iron = true
		#Generate Copper Ore
		copper = true
		#Generate Lapis Ore
		lapis = true
		#Generate Silver Ore
		silver = true
		#Generate Uranium Ore
		uranium = true
		#Generate Emerald Ore
		emerald = true
		#Generate Redstone Ore
		redstone = true

	[ore_generation.tin]
		#Set Tin Min Spawn Height (Default = 40)
		#Range: 0 ~ 120
		tinMinHeight = 40
		#Set Tin Max Spawn Height (Default = 110)
		#Range: 0 ~ 125
		tinMaxHeight = 110
		#Set Max Tin Vein Size (Default = 8)
		#Range: 0 ~ 32
		tinVeinSize = 8
		#Set Tin Spawn Chance (Default = 20)
		#Range: 0 ~ 64
		tinChance = 20

	[ore_generation.coal]
		#Set Coal Max Spawn Height (Default = 115)
		#Range: 0 ~ 125
		coalMaxHeight = 115
		#Set Coal Min Spawn Height (Default = 25)
		#Range: 0 ~ 120
		coalMinHeight = 25
		#Set Max Coal Vein Size (Default = 17)
		#Range: 0 ~ 64
		coalVeinSize = 17
		#Set Coal Spawn Chance (Default = 20)
		#Range: 0 ~ 64
		coalChance = 20

	[ore_generation.iron]
		#Set Iron Max Spawn Height (Default = 110)
		#Range: 0 ~ 125
		ironMaxHeight = 110
		#Set Iron Spawn Chance (Default = 20)
		#Range: 0 ~ 64
		ironChance = 20
		#Set Iron Min Spawn Height (Default = 40)
		#Range: 0 ~ 120
		ironMinHeight = 40
		#Set Max Iron Vein Size (Default = 8)
		#Range: 0 ~ 32
		ironVeinSize = 8

	[ore_generation.copper]
		#Set Max Copper Vein Size (Default = 8)
		#Range: 0 ~ 32
		copperVeinSize = 8
		#Set Copper Spawn Chance (Default = 20)
		#Range: 0 ~ 64
		copperChance = 20
		#Set Copper Min Spawn Height (Default = 35)
		#Range: 0 ~ 120
		copperMinHeight = 35
		#Set Copper Max Spawn Height (Default = 75)
		#Range: 0 ~ 125
		copperMaxHeight = 75

	[ore_generation.lapis]
		#Set Lapis Min Spawn Height (Default = 30)
		#Range: 0 ~ 120
		lapisMinHeight = 30
		#Set Max Lapis Vein Size (Default = 7)
		#Range: 0 ~ 36
		lapisVeinSize = 7
		#Set Lapis Spawn Chance (Default = 2)
		#Range: 0 ~ 64
		lapisChance = 2
		#Set Lapis Max Spawn Height (Default = 60)
		#Range: 0 ~ 125
		lapisMaxHeight = 60

	[ore_generation.silver]
		#Set Silver Min Spawn Height (Default = 30)
		#Range: 0 ~ 120
		silverMinHeight = 30
		#Set Max Silver Vein Size (Default = 9)
		#Range: 0 ~ 64
		silverVeinSize = 9
		#Set Silver Spawn Chance (Default = 4)
		#Range: 0 ~ 64
		silverChance = 4
		#Set Silver Max Spawn Height (Default = 60)
		#Range: 0 ~ 125
		silverMaxHeight = 60

	[ore_generation.uranium]
		#Set Uranium Spawn Chance (Default = 6)
		#Range: 0 ~ 64
		uraniumChance = 6
		#Set Uranium Max Spawn Height (Default = 125)
		#Range: 0 ~ 125
		uraniumMaxHeight = 125
		#Set Uranium Min Spawn Height (Default = 90)
		#Range: 0 ~ 120
		uraniumMinHeight = 90
		#Set Max Uranium Vein Size (Default = 4)
		#Range: 0 ~ 32
		uraniumVeinSize = 4

	[ore_generation.emerald]
		#Set Max Emerald Vein Size (Default = 4)
		#Range: 0 ~ 36
		emeraldVeinSize = 4
		#Set Emerald Spawn Chance (Default = 2)
		#Range: 0 ~ 32
		emeraldChance = 2
		#Set Emerald Max Spawn Height (Default = 55)
		#Range: 0 ~ 125
		emeraldMaxHeight = 55
		#Set Emerald Min Spawn Height (Default = 25)
		#Range: 0 ~ 120
		emeraldMinHeight = 25

	[ore_generation.redstone]
		#Set Redstone Spawn Chance (Default = 8)
		#Range: 0 ~ 64
		redstoneChance = 8
		#Set Redstone Max Spawn Height (Default = 115)
		#Range: 0 ~ 125
		redstoneMaxHeight = 115
		#Set Redstone Min Spawn Height (Default = 80)
		#Range: 0 ~ 120
		redstoneMinHeight = 80
		#Set Max Redstone Vein Size (Default = 8)
		#Range: 0 ~ 36
		redstoneVeinSize = 8

