
#Server and Client side changes.
[common]
	#Obsidian Spire rarity (higher number = lower spawnrate)
	obsidianSpireSpawnRate = 6
	#Elder Farlander house rarity (higher number = lower spawnrate)
	elderHouseSpawnRate = 10
	#Small Farlander house rarity (higher number = lower spawnrate)
	smallHouseSpawnRate = 9
	#Medium Farlander house rarity (higher number = lower spawnrate)
	mediumHouseSpawnRate = 9
	#Large Farlander house rarity (higher number = lower spawnrate)
	largeHouseSpawnRate = 9
	#Farlander Loot Well rarity (higher number = lower spawnrate)
	farlanderLootWellSpawnRate = 12

