
[General]
	#How much energy should the helmet use for every food eaten, when it is a powered helmet.
	#Range: 0 ~ 5000
	energy_consumption = 10
	#Can the helmet break while feeding? If this is false, the helmet stops feeding you when durability to low. Only when the helmet isn't powered by Energy.
	can_helmet_break = false
	#The here stated items can't be used as FeederHelmet
	helmet_blacklist = []
	#All here stated items are additionally to all default items eatable. This can be very dangerous, because it is possible that the helmet doesn't eat it, but uses it!!!
	food_whitelist = []
	#Put additional items to craft a helmet with a module in here. Up to 7
	additional_crafting_items = []
	#All here stated items aren't consumable by the FeederHelmet
	food_blacklist = []
	#Should the helmet wait until the food can be eaten completely, without any hunger loss by early eating?
	hungry_enough_wait = true
	#The here stated items can be used as Feeder Helmet, even when they aren't helmets at all (You can't put everything in you helmet slot)
	helmet_whitelist = []
	#How much durability should the helmet use for every food eaten, when it is a unpowered helmet.
	#Range: 0 ~ 64
	durability_consumption = 1
	#Defines how much ticks are between food checks. 20 ticks = 1 second
	#Range: 1 ~ 200
	feed_ticks = 20

