
#Theses options can only be modified on the server in multiplayer
[general]
	#Time to lose an energy point [5..MAX|default:5]
	#Range: > 5
	time_to_lose_energy = 5
	#Chance to get a Phial of Animation on boss [0..1000|default:10]
	#Range: 0 ~ 1000
	chance_drop_phial_of_animation_on_boss = 10
	#Maximum speed with no energy [0..300|default:30]
	#Range: 0 ~ 300
	speed_max_no_energy = 30
	#Maximum energy [100..MAX|default:1000]
	#Range: > 100
	max_energy = 1000
	#Acceleration increment [1..20|default:7]
	#Range: 1 ~ 20
	acceleration_increment = 7
	#Chance to fall with projectiles [0..100|default:10]
	#Range: 0 ~ 100
	chance_to_fall_with_projectile = 10
	#Time to recover an energy point [5..MAX|default:5]
	#Range: > 5
	timeToRecoverEnergy = 5
	#Maximum Speed [0..200|default:90]
	#Range: 0 ~ 200
	speed_max = 90
	#Allow special holiday events outside periods [false/true|default:true]
	persistant_holidays = true
	#Maximum acceleration [0..100|default:35]
	#Range: 0 ~ 100
	acceleration_max = 35
	#Allow special regeneration [false/true|default:true]
	allow_special_regen = true
	#Chance to get Halloween Sticks during this event [0..1000|default:10]
	#Range: 0 ~ 1000
	chance_drop_pumpkin_stick = 2
	#Allow flying in water [false/true|default:true]
	allow_to_fly_in_water = true
	#Defines the loottables having a chance to contain a Phial of Animation
	treasure_loot_table = ["minecraft:chests/end_city_treasure", "minecraft:chests/abandoned_mineshaft", "minecraft:chests/nether_bridge", "minecraft:chests/stronghold_library", "minecraft:chests/desert_pyramid", "minecraft:chests/jungle_temple", "minecraft:chests/igloo_chest", "minecraft:chests/woodland_mansion"]
	#Allow applying Soulbound [false/true|default:true]
	allow_tombstone_soulbound = true
	#Allow breaking plants [false/true|default:true]
	allow_to_break_plant = true

#Denied dimensions to ride a flying thing - example : minecraft:the_nether
[denied_dimensions_to_fly]
	#Dimensions for the brooms
	denied_dimension_broom = []
	#Dimensions for the carpets
	denied_dimension_carpet = []

