
#Theses options are custom parameters for the player
[client]
	#Height of the position of the bars [0..MAX|default:62]
	#Range: > 0
	bar_height_pos = 62
	#Enable rendering effects [false/true|default:true]
	render_effect = true
	#Length of the bars [9..182|default:182]
	#Range: 9 ~ 182
	bar_length = 182

