
#Common config for janoeo
[janoeo]
	#Nether ore generation: disable / enable
	netherOreGen = true
	#Dense ore generation: disable / enable
	denseOreGen = true
	#End ore generation: disable / enable
	endOreGen = true
	#Extra ore generation: disable / enable
	extraOreGen = false

