
[General]
	#The saturation increase. Example values: melon = 1.2, carrot = 3.6, chicken = 7.2, steak 12.8.
	#Range: 0.0 ~ 20.0
	saturationLevelIncrease = 10.0
	#The hunger level decreased. Example values: cookie = 2, bread = 5, salmon = 6, steak = 8.
	#Range: 0 ~ 20
	hungerLevelIncrease = 10

