
[Wither]

	[Wither.Minions]
		#Minimum Health with which Wither Minions can spawn with
		#Range: 0 ~ 1024
		"Min Health" = 10
		#As the Wither starts spawning Minions, every how much difficulty the Wither will spawn one more Minion
		#Range: > 1
		"Difficulty to Spawn One More Minion" = 2
		#Maximum amount of Wither Minions that can be around the Wither in a 24 block radius. After this number is reached the Wither will stop spawning minions. Set to 0 to disable this check
		#Range: > 1
		"Max Minions Around" = 16
		#After how many maximum ticks (20 ticks = 1 second) the wither will try to spawn Minions
		#Range: > 1
		"Max Cooldown" = 400
		#Maximum number of Wither Minions that a Wither can spawn. Set to 0 to disable Wither Minions
		#Range: > 0
		"Max Minions Spawned" = 8
		#Minimum Health with which Wither Minions can spawn with
		#Range: 0 ~ 1024
		"Max Health" = 20
		#After how many minimum ticks (20 ticks = 1 second) the Wither will try to spawn Minions. This is reduced by the current percentage health of the Wither, down to a minimum of 25% this value
		#Range: > 1
		"Min Cooldown" = 200
		#Minimum Difficulty required for the Wither will start spawning Wither Minions during the fight
		#Range: > 0
		"Difficulty to Spawn Minions" = 1

	[Wither.Health]
		#Increase Wither's Health by this value per difficulty
		#Range: 0.0 ~ 1.7976931348623157E308
		"Health Bonus per Difficulty" = 10.0
		#How many half hearts will the Wither regen more per difficulty. This doesn't affect the natural regeneration of the Wither (1 Health per Second). (E.g. By default, with 6 Withers spawned, the Wither will heal 1.3 health per second).
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Regeneration per Difficulty" = 0.05
		#Maximum bonus regeneration per second given by "Bonus Regeneration per Difficulty". Set to 0 to disable bonus health regeneration. This doesn't affect the natural regeneration of the Wither (1 Health per Second). It's not recommended to go over 1.0f without mods that adds stronger things to kill the Wither
		#Range: 0.0 ~ 1.7976931348623157E308
		"Maximum Bonus Regeneration" = 1.0

	[Wither.Armor]
		#How much armor points will have Withers per Difficulty
		#Range: 0.0 ~ 30.0
		"Bonus Armor per Difficulty" = 0.25
		#Maximum armor that Withers can spawn with
		#Range: 0.0 ~ 30.0
		"Maximum Armor" = 10.0

	[Wither.Rewards]
		#How much more experience (percentage) will Wither drop per Difficulty. The percentage is additive (e.g. with this set to 10%, 7 withers spawned = 70% more experience)
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Experience per Difficulty" = 10.0
		#Maximum chance to get a Nether Star shard.
		#Range: 0.0 ~ 100.0
		"Shards Max Chance" = 50.0
		#Maximum amount of shards that you can get from a Wither.
		#Range: > 0
		"Shards Max Count" = 8
		#Difficulty Divider for how many times the game tries to drop one more shard. Given this value x you get ((difficulty / x) + 1) times to get one or more shard.
		#E.g. By default, at 10 withers killed you have 6 times 20% chance to drop a shard.
		#Range: > 1
		"Shards Divider" = 2
		#How much chance per Difficulty to get a Nether Star Shard from killing the Wither
		#Range: 0.0 ~ 100.0
		"Shards per Difficulty" = 2.0

	[Wither.General]
		#If true and there are more players around the Wither, the Wither will have his stats based on the sum of both players difficulty. If false, the Wither stats will be based on the average of the difficulty of the players around
		"Sum Spawned Wither Difficulty" = false
		#The Maximum difficulty (times spawned) reachable by Wither. By default is set to 72 because the Wither reaches the maximum amount of health (1024, handled by Minecraft. Some mods can increase this) after 72 withers spawned.
		#Range: > 1
		"Max Difficulty" = 72
		#How much blocks from wither will be scanned for players to check for difficulty
		#Range: > 16
		"Spawn Radius Player Check" = 96

[Dragon]

	[Dragon.Larvae]
		#For each difficulty the Larvae spawn cooldown min and max values will be reduced by this value (E.g. with 10 difficulty and this set to 5, the Larvae cooldown min will be 550 and max 1150)
		#Range: > 0
		"Cooldown Reduction Per Difficulty" = 10
		#As the Ender Dragon Difficulty reaches this value she will be spawning a Larva during the fight. Plus every time Difficulty is a multiplier of this value the Ender Dragon will spawn one more Larva
		#Range: > 1
		"Difficulty to Spawn One More Larva" = 1
		#Maximum number of Larvae that an Ender Dragon can spawn. Set to 0 to disable Dragon's Larvae
		#Range: > 0
		"Max Larvae Spawned" = 6
		#After how many maximum ticks (20 ticks = 1 second) the Ender Dragon will try to spawn Larvae
		#Range: > 1
		"Max Cooldown" = 1200
		#After how many minimum ticks (20 ticks = 1 second) the Ender Dragon will try to spawn Larvae
		#Range: > 1
		"Min Cooldown" = 1050

	[Dragon.Health]
		#Increase Ender Dragon's Health by this value per difficulty
		#Range: 0.0 ~ 1.7976931348623157E308
		"Health Bonus per Difficulty" = 10.0
		#How many half hearts will the Ender Dragon regen per difficulty. This doesn't affect the regeneration of the Ender Dragon from Crystals. (E.g. With 6 Dragons killed, the Dragon will heal 0.6 health per second without Crystals).
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Regeneration per Difficulty" = 0.025
		#Maximum bonus regeneration per second given by "Bonus Regeneration per Difficulty". Set to 0 to disable bonus health regeneration. This doesn't affect the regeneration of the Ender Dragon from Crystals. It's not recommended to go over 1.0f without mods that adds stronger things to kill the Ender Dragon
		#Range: 0.0 ~ 1.7976931348623157E308
		"Maximum Bonus Regeneration" = 0.5

	[Dragon.Minion]
		#For each difficulty the Minion spawn cooldown min and max values will be reduced by this value (E.g. with 10 difficulty and this set to 10, the Minion cooldown min will be 1100 and max 1700)
		#Range: > 0
		"Cooldown Reduction Per Difficulty" = 10
		#After how many maximum ticks (20 ticks = 1 second) the Ender Dragon will try to spawn a Minion
		#Range: > 1
		"Max Cooldown" = 1800
		#After how many minimum ticks (20 ticks = 1 second) the Ender Dragon will try to spawn a Minion
		#Range: > 1
		"Min Cooldown" = 1200
		#Minimum Difficulty required for the Ender Dragon to start spawning Dragon's Minions during the fight. Set to -1 to disable Dragon's Minions spawning
		#Range: > 0
		"Difficulty to Spawn Minions" = 1

	[Dragon.Rewards]
		#How much more experience (percentage) will Ender Dragon drop per Difficulty. The percentage is additive (e.g. with this set to 10%, 7 Ender Dragons killed = 70% more experience)
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Experience per Difficulty" = 10.0
		#Should the first Dragon killed per Player always drop the egg and the first Dragon experience (12k instead of 500)? If true means that every player will get the Dragon Egg as they kill their first Dragon (yes even when 2 players kill the dragon)
		"First Dragon per Player" = true

	[Dragon.General]
		#The Maximum difficulty (times killed) reachable by Ender Dragon. By default is set to 82 because the Ender Dragon reaches the maximum amount of health (1024, handled by Minecraft. Some mods can increase this) after 82 Dragons killed.
		#Range: > 1
		"Max Difficulty" = 82
		#If true and there are more players around the Dragon, she will have his stats based on the sum of both players' difficulty. If false, the Dragon stats will be based on the average of the difficulty of the players around.
		"Sum Killed Dragons Difficulty" = false

	[Dragon.Attack]
		#How much more percentage damage does the Ender Dragon deal per difficulty? Setting to 0 will disable this feature
		#Range: 0.0 ~ 1.7976931348623157E308
		"Bonus Attack Damage" = 15.0
		#Normally the Ender Dragon attacks only when leaving the center platform. With this active she has a chance each tick (1/20th of second) when roaming around to attack the player.\nThis defines the chance to attack the player each tick when all the crystals were destoyed and the difficulty is 24 (last End Gate to appear). The actual formula is\n(this_value / 23) * difficulty * (1 / remaining_crystals).\nSetting to 0 will disable this feature.
		#Range: 0.0 ~ 1.7976931348623157E308
		"Charge Player Base Chance" = 0.5

