
[general]
	#Should the Log4J root logger be filtered?
	filterLog4JRoot = true
	#Should Java's system output stream be filtered?
	filterJavaOut = true
	#Should Java loggers be filtered?
	filterJavaLogger = true
	#Should misc Log4J loggers be filtered?
	filterLog4JMisc = true

[filters]
	#A list of regex filters. Messages will be filtered if they match any of the defined regex patterns.
	regex = []
	#A list of basic filters. Messages will be filtered if they contain any basic filter as a substring.
	basic = []

