
[general]
	#Time before explosion in ticks
	#Range: > 1
	timer = 200
	#Enable integration with Cursed Earth
	"cursed earth integration" = true
	#Allowed Container Types
	containers = ["minecraft:crafting", "fastbench:fastbench"]

