
[general]
	#Set to true to force crafting recipes to require treated water for VFP's food recipes. Defaults false unless a mod like Tough As Nails is present. Does not require these other mods be present to set true! Requires restart if changed.
	treat_raw_water = "*DEFAULT*"
	#Set to true to force all the basic recipes to use a mod-specific element to ensure no collisions with other mod recipes. Off by default; requires restart if changed.
	super_compatibility_mode = false
	#Set to true to allow player to instantly consume soaked VFP foods and bootleg gelos on right-click. This option is independent of the 'insta_eat_morsels' option. Disabled by default.
	insta_eat_soaked = false
	#INTERNAL. Development workflow enabled. Do NOT enable in regular environment.
	debug_mode = false
	#Set to true to have VFP create single-use food items if possible. 'If possible' is defined as having a total food value less than or equal to the max food points allowed by vanilla Minecraft (20pts). Off for most multi-use capable foods by default. Requires restart if changed.
	prefer_singleuse = "*DEFAULT*"
	#Set to false to disable breeding polar bears with raw salmon. Enabled by default; requires restart if changed.
	polarbear_breeding = true
	#Set to false to disable generation of experience from crafting foods using VFP's mechanism. Note that this option does not affect cooking or mining experience drops or Xp generated by other mods. Enabled by default; requires restart if changed.
	crafting_xp_enabled = true
	#Set to false to turn off documentation tooltips (status tips not affected). Enabled by default.
	show_doc_tooltips = true
	#Set to false to disable all moonshine potions (tonics) and bootleg gelos features. Does not affect availability of VFP's custom potions. Existing items will still work. Enabled by default; requires restart if changed.
	moonshine_mixing_enabled = true
	#Set to true to limit the use of the flint-cutter to only food RELATED recipes. Disabled by default (cutter can be used to cut things like wool blocks and leather).
	flint_cutter_for_food_only = false
	#Set to true to disable extra recipes and actions that allow players access to items normally tied to standard progression. For example, if true, disables recipes for blaze powder and ender pearls. Combine with other options to remove all possible vanilla progression changes.
	strict_progression = "*DEFAULT*"
	#Set to false to distribute VFP items and blocks to vanilla tabs in creative views (VFP table is removed). Enabled by default.
	use_custom_tab = true
	#Set to false to disable -ALL- custom VFP drops from blocks and mobs unconditionally. Overrides all other settings. OFF by default. Requires restart if changed.
	drops_enabled = true
	#Set to false to disable compensation for Minecraft ignoring small amounts of crafting Xp. Note that this option is ignored if crafting Xp is disabled. Enabled by default; requires restart if changed.
	generous_xp = true
	#Set to true to allow player to instantly consume VFP morsels on right-click. Morsels are defined as any consumable item with less than 4pts of food value. Disabled by default.
	insta_eat_morsels = false
	#Set to false to disable generation of custom VFP ores like rock salt and natron in new worlds and new chunks. Enabled by default; requires restart if changed.
	ore_generate_enabled = true
	#Set to false to disable all mod-specific additions to structure and activity loot tables. Changing this affects things like fishing and dungeon loot but NOT upsize drops (see individual options). Enabled by default; requires restart if changed.
	enrich_loot_tables = true
	#Set to false to disable installation of VFP's potions like Wolf's Spirit potion. Does NOT affect adhoc mixing of existing potions into moonshine potions or the temperature effects of chilled and heated foods. Enabled by default. Requires restart if changed.
	potions_enabled = true
	#Set to false to disable seed drying from source produce. By default you can use seed drying paper to extract seeds from melons, pumpkins, wheat, and a few modded crops. Enabled by default; requires restart if changed.
	seed_drying_enabled = true

[integration]
	#Set to false to disable direct integration with villager merchant trades tables and trading mods like FarmingForBlockheads. Leave as '*DEFAULT*' to permit trading depending on context and availability of other mods.
	modded_trading_allowed = "*DEFAULT*"
	#Set to false to disable builtin reheating and chilling recipes. You can still provide hot/cold foods via loot tables, trading, and shops (modded). This option does NOT alter any bonus effects from consuming such foods. Enabled by default; requires restart if changed.
	hotcold_food_crafting = true
	#Set to true to show all of the mod's items whether or not they are directly obtainable by the player using a VFP-made recipe. This option is useful if you want to see what items are available when requisite food or materials are provided by other means like merchants, quests, etc. Disabled by default.
	show_all_items_in_ui = false
	#Set to false to disable direct recipe making with non-vanilla and non-VFP foodstuffs (for example using Harvestcraft DIRECTLY). Does not affect tag-based recipe ingredients. Enabled by default; requires restart if changed.
	modded_ingredients = true

	[integration.smarthoppers]
		#Set to false to disable integration with SmartHoppers mod's various auto-crafting hoppers. Enabled by default; requires restart if changed.
		auto_integrate = true

	[integration.vanilla]
		#Set to false to disable crafting of Lava Sand to blaze rods, magma cream, fire charges, and eyes of ender. Basically affects any recipe that uses lava sand instead of blaze powder. Ignored if strict vanilla progression enabled.
		lava_sand_to_blaze_rods = true
		#Set to false to disable smelting of Ink Pearls to ender pearls. Ignored if strict vanilla progression enabled.
		ink_pearls_to_ender_pearls = true
		#Set to false to disable crafting of dragon's breath using Guardian Air Sacs. Ignored if strict vanilla progression or guardian drops are disabled.
		airsac_to_dragon_breath = true
		#Set to false to disable crafting of 'Exo' shulker boxes using guardian drops. Ignored if strict vanilla progression or guardian drops are disabled.
		guardian_fins_to_shulkerbox = true
		#Set to false to disable extra craft recipes for water buckets and bottles; for instance the recipe to convert ice blocks to buckets of water.
		extra_water_crafting = true
		#Set to false to disable upsizing of wool drops from sheep-- VFP will no longer ensure at least 3 wool blocks are dropped per kill. Ignored if strict vanilla progression or general drops upsizing option disabled.
		upsized_wool_drops = false
		#Set to false to disable substitution of Animal Hide Straps as 'string' in some recipes. Ignored if strict vanilla progression is enabled.
		straps_as_string = false
		#Set to true to enable Felis Life Essence based craft recipes for some spawn eggs. Disabled by default; requires restart if changed. Ignored if strict vanilla progression is enabled.
		spawnegg_crafting = false

[butcher]
	#Set to true to enable mod bone drops regardless of the other mods present and super-compatibility mode setting. Leave as *DEFAULT* to let VFP decide if bone drops are appropriate per animal type. Requires game restart if changed.
	include_bone_drops = "*DEFAULT*"
	#Set to true to guarantee a minimum amount of items are dropped from killing cows, pigs, sheep, etc. The meat drop increase is from 0 to 3 more pieces with other items like hides, feathers, shells, and bones also guaranteed (1 per kill) unless blocked by another config option. This option applies to standard Minecraft mobs only. Enabled by default; requires restart if changed. Ignored if mod drops disabled.
	ensure_death_drops = false
	#Set to false to disable mod drops from killing wolves (tamed and untamed). VFP adds raw wolf meat and special drops for custom potions. Enabled by default.
	include_wolf_drops = true
	#Set to true to have llamas drop regular (sheep) wool blocks instead of the custom VFP fleece wool blocks. Disabled by default. Ignored if llama drops in general are disabled.
	llamas_drop_wool = false
	#Set to false to disable mod drops from killing llamas. VFP adds raw llama meat and fleece (like wool) blocks. Enabled by default.
	include_llama_drops = true
	#Set to false to disable mod drops from killing guardians and elder guardians. VFP adds guardian air sacs, tail fins, meat, and other items. Enabled by default.
	include_guardian_drops = true
	#Set to true to disable ONLY meat drops from killing guardians when 'include_guardian_drops' is enabled; ignored otherwise. Use if you're interested in tail fins and air sac drops only.
	exclude_guardian_meat = false
	#Set to true to disable ONLY meat drops from killing ravagers when 'include_ravager_drops' is enabled; ignored otherwise. Use if you're interested in bone and horn drops only.
	exclude_ravager_meat = false
	#Set to false to disable mod drops from killing a bat. VFP adds bat meat, bat poop (use like bonemeal or to create rotten flesh), and special drops for potions. Enabled by default.
	include_bat_drops = true
	#Set to true to disable ONLY meat drops from killing wolves when 'include_wolf_drops' is enabled; ignored otherwise. Use if you have another mod that already drops wolf meat.
	exclude_wolf_meat = false
	#Set to true to disable ONLY meat drops from killing polar bears when 'include_polarbear_drops' is enabled; ignored otherwise. Use if you have another mod that already drops polar bear meat.
	exclude_polarbear_meat = false
	#Set to true to disable ONLY meat drops from killing llamas when 'include_llama_drops' is enabled; ignored otherwise. Use if you have another mod that already drops llama meat.
	exclude_llama_meat = false
	#Set to false to disable mod drops from killing horses. VFP adds drops like raw horse meat and horse tears for brewing potions. Enabled by default.
	include_horse_drops = true
	#Set to true to disable ONLY meat drops from killing horses when 'include_horse_drops' is enabled; ignored otherwise. Use if you have another mod that already drops horse meat.
	exclude_horse_meat = false
	#Set to true to disable ONLY meat drops from killing squid when 'include_squid_drops' is enabled; ignored otherwise. Use if you have another mod that already drops squid meat.
	exclude_squid_meat = false
	#Set to false to disable mod drops from killing ravager beasts. VFP adds ravager meat, bones, and other items used in potion brewing. Enabled by default.
	include_ravager_drops = true
	#Set to false to disable mod drops from killing zombies of all kinds. VFP adds tainted souls for use with Felis Life Essence in potion brewing. Enabled by default.
	include_zombie_drops = true
	#Set to false to disable mod drops from killing baby cows. VFP adds calf stomach lining for use in creating curdling agent for cheese. Enabled by default.
	include_calf_drops = true
	#Set to false to disable mod drops from killing pigs. VFP adds drops like raw pork hocks and pig tails for intriguing culinary delights. Enabled by default.
	include_pig_drops = true
	#Set to false to disable mod drops from killing polar bears. VFP adds raw  bear meat and special drops for custom potions. Enabled by default.
	include_polarbear_drops = true
	#Set to true to enable mod drops from killing phantoms. VFP adds phantom meat and other items used in potion brewing. Disabled by default.
	include_phantom_drops = false
	#Set to false to disable mod drops from killing squid. VFP adds raw squid meat and ink pearl fragment drops from squid. Enabled by default.
	include_squid_drops = true
	#Set to false to disable the ability to steal lives from ocelots as Felis Life  Essence. Also controls Bane of Ocelot drop from creepers. Enabled by default.
	include_ocelot_drops = true

[upsizer]
	#Max stack size for all bottled items like fizzy drinks and juices. Default stack size is 24. Allowed sizes are [1,4,8,16,24,32,64].
	drinks_max_stacksize = 24
	#Set to the max number of distinct potions allowed in a single moonshine mixture. Hard-limit is 12. Set to one (1) to disable moonshine mixing but keep potion-to-tonic conversion for stackable potions.
	moonshine_max_potions = 7
	#Max stack size for all soupy items like creamy soups, chowders, and stews. Default stack size is 24. Allowed sizes are [1,4,8,16,24,32,64].
	soups_max_stacksize = 24

[produce]
	#Set to true to enable (un)crafting of 9 mushrooms from standard mushroom blocks. If enabled you can increase storage size of mushrooms per slot and unlock all the mushroomy goodness of giant mushrooms! Disabled by default.
	mushroom_pantry_blocks = false
	#Set to false to stop acorn drops when you break oak and dark-oak leaves. Will not disable acornmeal based recipes (as acorns can be obtained from other mods). Enabled by default.
	include_acorn_drops = true
	#Set to false to disable additional mushroom drops from chopping down huge mushrooms with a butchering axe or other tool with fortune enchantment. Also adds mushrooms to mooshroom drops. Enabled by default. Needs restart if changed.
	upsize_mushroom_drops = true
	#Set to false to stop spruce tip drops when you break spruce leaves with sticks. Enabled by default.
	include_spruce_tip_drops = true
	#Set to false to stop raftugli fruit drops when you break jungle leaves. Enabled by default.
	include_raftugli_drops = true

[misc]
	#Set to false to disable decker sandwich ingredient (name) tooltips. If enabled you will see the name of each food item that went into your decker sandwich. Overrides the general 'show_doc_tooltips' option. Enabled by default.
	show_sandwich_ingredients = true

