
#Modification of vanilla_recipes recipes and addition of new recipes regarding vanilla_recipes
[Crafting]
	#Have wool but need string?
	string = true
	#Cobblestone used in stone tools doesn't make sense?
	betterStoneTools = true
	#Tired of not having a nametag?
	nametag = true
	#Wanna craft multiple chests at one go?
	betterChest = true
	#Want 8 stairs rather than 4 in stairs recipe?
	betterStairs = true

