
[oregeneration]
	#Determines the rarity of amber veins.
	#Range: 1 ~ 200
	amber_weight = 2
	#Determines the rarity of rockroot veins.
	#Range: 1 ~ 200
	rockroot_weight = 16
	#Determines the rarity of fiery glass veins.
	#Range: 1 ~ 200
	fiery_glass_weight = 6
	#Determines the size of an amber vein.
	#Range: 1 ~ 32
	amber_size = 8
	#Determines the size of a moonstone vein.
	#Range: 1 ~ 32
	moonstone_size = 8
	#Determines the rarity of moonstone veins.
	#Range: 1 ~ 200
	moonstone_weight = 5
	#Determines the size of a fiery glass vein.
	#Range: 1 ~ 32
	fiery_glass_size = 8
	#Whether to have ores from this mod spawn at all.
	generate_ores = true
	#Determines the size of a rockroot vein.
	#Range: 1 ~ 32
	rockroot_size = 3

[toolcontrollers]
	#Decides what blocks are allowed and not allowed to be affected by the sickle.
	#Adding '+' to the start of the block will add it, and '-' will remove it.
	sickle_block_list = []

[droprate]
	#Rate of hemp seed drops from grass blocks.
	#Range: 0 ~ 100
	hemp_seed_rate = 8
	#Whether to have seeds from this mod drop from grass at all.
	drop_seeds = true

[entityspawning]
	#List of biome types from the biome dictionary that the dreadfish cannot spawn in. Define as strings with "s and separate with a comma.
	dreadfish_exclusions = ["NETHER", "END"]
	#Maximum size of the group when spawned.
	#Range: 1 ~ 200
	lunar_moth_max_group_size = 5
	#Maximum size of the group when spawned.
	#Range: 1 ~ 10
	dreadfish_max_group_size = 3
	#Minimum size of the group when spawned.
	#Range: 1 ~ 200
	lunar_moth_min_group_size = 2
	#Minimum size of the group when spawned.
	#Range: 1 ~ 200
	beetle_min_group_size = 1
	#Minimum size of the group when spawned.
	#Range: 1 ~ 5
	dreadfish_min_group_size = 1
	#List of biome types from the biome dictionary that lunar moths cannot spawn in. Define as strings with "s and separate with a comma.
	lunar_moth_exclusions = ["DENSE"]
	#Allow beetles to spawn?
	beetle_spawn = true
	#Maximum size of the group when spawned.
	#Range: 1 ~ 200
	beetle_max_group_size = 2
	#List of biome types from the biome dictionary that beetles cannot spawn in. Define as strings with "s and separate with a comma.
	beetle_exclusions = [""]
	#List of biome types from the biome dictionary that the lunar moth can spawn in. Define as strings with "s and separate with a comma.
	lunar_moth_biomes = ["FOREST", "PLAINS", "MOUNTAIN", "HILLS"]
	#Allow dreadfish to spawn?
	dreadfish_spawn = true
	#Determines the rarity of the dreadfish.
	#Range: 1 ~ 100
	dreadfish_weight = 24
	#List of biome types from the biome dictionary that the dreadfish can spawn in. Define as strings with "s and separate with a comma.
	dreadfish_biomes = ["SNOWY", "COLD"]
	#Determines the rarity of the lunar moth.
	#Range: 1 ~ 200
	lunar_moth_weight = 2
	#Determines the rarity of the beetle.
	#Range: 1 ~ 200
	beetle_weight = 5
	#List of biome types from the biome dictionary that the beetle can spawn in. Define as strings with "s and separate with a comma.
	beetle_biomes = ["CONIFEROUS", "FOREST", "JUNGLE", "DENSE"]
	#Allow lunar moths to spawn?
	lunar_moth_spawn = true

