
[capsule]
	# This number decides that how many effect names are render behind the capsule name
	#Range: 0 ~ 5
	effectRenderCount = 3

[misc]
	# Set this to true will render the icon in the ingame HUD. This is false by default
	renderNVNFHUD = false

