#Whether the search bar will be focused by default when opening containers
autoFocus = false
#Minimum size a container must be for a search bar to be added
#Range: > 0
minimumContainerSize = 27
#Comma separated list of containers in which the search bar should be disabled. Name should be that which appears in the top left of the container's GUI. Example: blacklist=["Chest", "Large Chest"]
blacklist = ["Crafting Station", "Ender Chest Backpack", "Medium Backpack", "Large Backpack", "Dimensional Chest", "Travel Bag", "Ender Bag", "Orange Ender Bag", "Magenta Ender Bag", "Light Blue Ender Bag", "Yellow Ender Bag", "Lime Ender Bag", "Pink Ender Bag", "Gray Ender Bag", "Light Gray Ender Bag", "Cyan Ender Bag", "Purple Ender Bag", "Blue Ender Bag", "Brown Ender Bag", "Green Ender Bag", "Red Ender Bag", "Black Ender Bag", "Dank 3", "Dank 4", "Dank 5", "Dank 6", "Dank 7"]

