
#Re-adds sword blocking in a very configurable way.
[sword_blocking]
	#Percentage an incoming attack will be reduced by when blocking.
	#Range: 0.0 ~ 1.0
	"Blocked Damage Ratio" = 0.5
	#Damage sword when blocking an attack depending on the amount of damage blocked. Sword is only damaged when at least three damage points have been blocked, just like a shield.
	"Damage Sword" = false
	#Swords to exclude from blocking. Intended for modded swords that already have their own right-click function. Format for every entry is "<namespace>:<id>".
	"Blocking Exclusion List" = []
	#Incoming projectiles such as arrows or tridents will ricochet while blocking.
	"Deflect Projectiles" = false
	#Amount of ticks after which blocking using a sword is effective.
	#Range: 0 ~ 72000
	"Warm-Up Delay" = 0
	#Items to include for blocking. Intended for modded swords that don't extend vanilla swords. Format for every entry is "<namespace>:<id>".
	"Blocking Inclusion List" = []

#Restores pre-combat update combat mechanics.
[classic_combat]
	#Boost sharpness enchantment to add +1.0 attack damage per level instead of +0.5 damage.
	"Boost Sharpness" = false
	#Prevent particles created by a sweep attack from appearing.
	"No Sweeping Particles" = false
	#Don't automatically stop sprinting when attacking.
	"Sprint While Attacking" = true
	#Is the sweeping edge enchantment required to perform a sweep attack.
	"Require Sweeping Edge" = false
	#Completely remove the attack cooldown as if it never even existed in the first place.
	"Remove Attack Cooldown" = false

#Allows changing various stats of items, mainly for restoring pre-combat update values.
[material_changer]
	#Specify a value ADDED to the attack damage attribute for any item. Format for every entry is "<namespace>:<id>,<value>".
	"Attack Damage List" = ["minecraft:diamond_sword,1.0", "minecraft:diamond_axe,-2.0", "minecraft:diamond_pickaxe,1.0", "minecraft:diamond_shovel,-0.5", "minecraft:diamond_hoe,3.0", "minecraft:iron_sword,1.0", "minecraft:iron_axe,-3.0", "minecraft:iron_pickaxe,1.0", "minecraft:iron_shovel,-0.5", "minecraft:iron_hoe,2.0", "minecraft:stone_sword,1.0", "minecraft:stone_axe,-4.0", "minecraft:stone_pickaxe,1.0", "minecraft:stone_shovel,-0.5", "minecraft:stone_hoe,1.0", "minecraft:wooden_sword,1.0", "minecraft:wooden_axe,-3.0", "minecraft:wooden_pickaxe,1.0", "minecraft:wooden_shovel,-0.5", "minecraft:golden_sword,1.0", "minecraft:golden_axe,-3.0", "minecraft:golden_pickaxe,1.0", "minecraft:golden_shovel,-0.5"]
	#Change the durability for any tool. Setting it to 0 will make the tool unbreakable. Format for every entry is "<namespace>:<id>,<value>".
	"Tool Durability List" = []
	#Specify a value ADDED to the attack speed attribute for any item. Not compatible with "classic_combat" features. Format for every entry is "<namespace>:<id>,<value>".
	"Attack Speed List" = []
	#Specify the max stack size for any item. Value has to be between 0 and 64. Format for every entry is "<namespace>:<id>,<value>".
	"Max Stack Size List" = ["minecraft:snowball,64", "minecraft:ender_eye,16"]

#Introduces various changes from current combat snapshots.
[modern_combat]
	#Disables the default 0.5 second damage immunity when hit by a projectile. This makes it possible for entities to be hit by multiple projectiles at once, e. g. from a multishot enchanted crossbow.
	"No Projectile Immunity" = true
	#Items to add a delay in ticks to after using. Doesn't override a delay an item has by default.
	"Item Delay List" = ["minecraft:snowball,4", "minecraft:egg,4"]
	#Makes the impaling enchantment apply when attack any creature in contact with rain or water; not just to aquatic mobs.
	"Boost Impaling" = true
	#Only damages axes by 1 durability instead of 2 when attacking so they properly be used as weapons.
	"No Axe Attack Penalty" = true
	#Allow tridents to be fired from dispensers.
	"Dispense Tridents" = true
	#Amount of ticks after which blocking using a shield is effective. Used to be 5 ticks before combat snapshots.
	#Range: 0 ~ 72000
	"Shield Warm-Up Delay" = 0

#Changes the way the player heals from food.
[food_buffs]
	#Food level required to be able to regenerate health. Only applies when "Food Ticker" is set to "CUSTOM".
	#Range: 0 ~ 20
	"Regeneration Food Level" = 18
	#Drain food instead of saturation when regenerating. Only applies when "Food Ticker" is set to "CUSTOM".
	"Regenerate From Food" = false
	#Amount of ticks it takes to consume a food item. Vanilla default is 32.
	#Range: 0 ~ 72000
	"Eating Speed" = 32
	#Food level from which on sprinting is disabled. Set to "-1" to always allow sprinting.
	#Range: -1 ~ 20
	"Sprinting Level" = 5
	#"CLASSIC" option restores the pre-combat update system, "COMBAT" option introduces the changes from current combat snapshots, "CUSTOM" allows custom values to be supplied.
	#Allowed Values: DEFAULT, CLASSIC, COMBAT, CUSTOM
	"Food Ticker" = "DEFAULT"
	#Amount of ticks between regenerating when enough food is present. Only applies when "Food Ticker" is set to "CUSTOM".
	#Range: > 0
	"Regeneration Delay" = 80

