
["Basic Ender Gate"]
	#Range: min = 0, max = 2147483647
	transfer = "1000"
	#Range: min = 1, max = 16
	channels = "2"

["Hardened Ender Gate"]
	#Range: min = 0, max = 2147483647
	transfer = "5000"
	#Range: min = 1, max = 16
	channels = "4"

["Blazing Ender Gate"]
	#Range: min = 0, max = 2147483647
	transfer = "12000"
	#Range: min = 1, max = 16
	channels = "7"

["Niotic Ender Gate"]
	#Range: min = 0, max = 2147483647
	transfer = "32000"
	#Range: min = 1, max = 16
	channels = "11"

["Spirited Ender Gate"]
	#Range: min = 0, max = 2147483647
	transfer = "74000"
	#Range: min = 1, max = 16
	channels = "16"

