
#Range: min = 0, max = 2147483647
["Basic Energy Cable"]
	transfer = "2000"

["Hardened Energy Cable"]
	transfer = "10000"

["Blazing Energy Cable"]
	transfer = "40000"

["Niotic Energy Cable"]
	transfer = "200000"

["Spirited Energy Cable"]
	transfer = "1000000"

