#
#List of fluids used in Magmatic Generator.
#fluid registry name = heat per 100 mb eg: ["minecraft:lava=10000", "examplemod:fluid=1000"]
#Min = 1, max = 2147483647
magmaticFluids = ["minecraft:lava=10000"]
#Enable this to allow other mods to add their fluids. [default:true]
magmaticFluidsAPI = true

#Range: min = 0, max = 2147483647
["Basic Magmatic Generator"]
	transfer = "120"
	perTick = "90"
	capacity = "50000"

["Hardened Magmatic Generator"]
	transfer = "400"
	perTick = "220"
	capacity = "100000"

["Blazing Magmatic Generator"]
	transfer = "900"
	perTick = "500"
	capacity = "500000"

["Niotic Magmatic Generator"]
	transfer = "3000"
	perTick = "2400"
	capacity = "1000000"

["Spirited Magmatic Generator"]
	transfer = "20000"
	perTick = "10000"
	capacity = "5000000"

