
#Range: min = 0, max = 2147483647
["Player Transmitter"]
	transfer = "100"
	capacity = "10000"

["Dimensional Player Transmitter"]
	transfer = "250"
	capacity = "100000"

["Energy Discharger"]
	transfer = "1000"
	capacity = "500000"

["Energy Hopper"]
	transfer = "1000"
	capacity = "500000"

